version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shop_network
    depends_on:
      - jsonserver
  jsonserver:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shop_network
networks:
  shop_network:
    driver: bridge
