version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shop_network
    depends_on:
      - jsonserver
  jsonserver:
    image: clue/json-server
    volumes:
      - ./db.json:/data/db.json
    networks:
      - shop_network
networks:
  shop_network:
    driver: bridge

